name: Scope Testing

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Dependencies`
      run: rake dependencies
    - name: Scope for Swift
      uses: undefinedlabs/scope-for-swift-action@v1
      with:
        dsn: ${{ secrets.SCOPE_DSN }}
        workspace: WordPress.xcworkspace
        scheme: WordPress
        codePath: true
      env:
        SCOPE_INSTRUMENTATION_HTTP_PAYLOADS: YES
